import type { ModuleDefinition } from "@/lib/recommendation/types";

export const modules: Record<string, ModuleDefinition> = {
  MODULE_A_FOCUS: {
    id: "MODULE_A_FOCUS",
    name: "Cognitive Edge",
    tagline: "For focus, memory, and mental stamina",
    ingredients: [
      {
        name: "Lion's Mane (Hericium erinaceus)",
        dose: "500mg",
        purpose: "Nerve growth, memory, cognitive repair",
        why: "Lion's mane is studied for its effect on nerve growth factor pathways and cognitive maintenance.",
        research: {
          citation: "Mori et al., Phytotherapy Research, 2009",
          tested: "Lion's mane vs placebo on cognitive function",
          found: "Cognitive scores improved through the supplementation period",
          meaning: "This module is for people whose answers point to fog and slower recall.",
        },
        timing: "AM",
      },
      {
        name: "Bacopa Monnieri (45% bacosides)",
        dose: "300mg",
        purpose: "Memory consolidation, calm focus",
        why: "Bacopa is studied for memory and information processing support and tends to build over weeks rather than days.",
        research: {
          citation: "Roodenrys et al., Neuropsychopharmacology, 2002",
          tested: "Bacopa vs placebo on working memory",
          found: "Working memory and processing speed improved",
          meaning: "This is a cumulative ingredient rather than an acute stimulant.",
        },
        timing: "AM — with food",
      },
      {
        name: "L-Theanine",
        dose: "200mg",
        purpose: "Focused calm, attention support",
        why: "L-theanine is studied for relaxed alertness and for smoothing the edge of caffeine without flattening attention.",
        research: {
          citation: "Nobre et al., Asia Pacific Journal of Clinical Nutrition, 2008",
          tested: "L-theanine + caffeine on attention tasks",
          found: "Performance improved versus caffeine alone",
          meaning: "Useful when the pattern is distracted intensity rather than low drive.",
        },
        timing: "AM",
      },
    ],
  },
  MODULE_B_METABOLIC: {
    id: "MODULE_B_METABOLIC",
    name: "Metabolic Support",
    tagline: "For energy stability, blood sugar support, and cellular efficiency",
    ingredients: [
      {
        name: "Berberine HCl",
        dose: "500mg",
        purpose: "Blood sugar support, metabolic efficiency",
        why: "Berberine is studied for metabolic support and is included when answers suggest post-meal instability.",
        research: {
          citation: "Zhang et al., Evidence-Based Complementary and Alternative Medicine, 2010",
          tested: "Berberine on metabolic markers over 3 months",
          found: "Glucose-related markers improved in the supplementation group",
          meaning: "Included for patterns tied to post-meal crashes rather than for general use.",
        },
        timing: "With largest meal of the day",
      },
      {
        name: "CoQ10 (Ubiquinol form)",
        dose: "100mg",
        purpose: "Mitochondrial energy production, cellular repair",
        why: "CoQ10 supports mitochondrial energy pathways and is useful when fatigue appears cellular rather than motivational.",
        research: {
          citation: "Mizuno et al., Nutrition, 2008",
          tested: "CoQ10 supplementation on fatigue markers",
          found: "Fatigue and performance markers improved",
          meaning: "This ingredient targets energy production rather than masking tiredness.",
        },
        timing: "AM — with food",
      },
      {
        name: "Alpha-Lipoic Acid",
        dose: "300mg",
        purpose: "Antioxidant support, glucose metabolism",
        why: "ALA supports glucose metabolism and works across both fat and water environments in the body.",
        research: {
          citation: "Udupa et al., Journal of Diabetes & Metabolic Disorders, 2014",
          tested: "ALA supplementation on oxidative stress and blood glucose markers",
          found: "Fasting glucose and oxidative stress markers improved",
          meaning: "Rounds out the metabolic module with mechanistic support.",
        },
        timing: "PM — away from meals",
      },
    ],
  },
  MODULE_C_STRESS: {
    id: "MODULE_C_STRESS",
    name: "Cortisol Armor",
    tagline: "For stress resilience, nervous system recovery, and quality downtime",
    ingredients: [
      {
        name: "Rhodiola Rosea (3% rosavins)",
        dose: "200mg",
        purpose: "Stress adaptation, mental fatigue support",
        why: "Rhodiola is studied for mental fatigue under stress and for maintaining useful alertness under load.",
        research: {
          citation: "Shevtsov et al., Phytomedicine, 2003",
          tested: "Rhodiola vs placebo on fatigue and mental performance",
          found: "Mental performance held up better under stress",
          meaning: "This supports the person who feels mentally done too early in the day.",
        },
        timing: "AM — before demanding periods",
      },
      {
        name: "Phosphatidylserine",
        dose: "100mg",
        purpose: "Cortisol modulation, memory support",
        why: "Phosphatidylserine supports membrane health and is studied for stress response modulation.",
        research: {
          citation: "Benton et al., Nutritional Neuroscience, 2001",
          tested: "Phosphatidylserine on cognitive function and cortisol response",
          found: "Stress response markers improved",
          meaning: "This is about steadier function under pressure, not sedation.",
        },
        timing: "AM",
      },
      {
        name: "L-Theanine",
        dose: "200mg",
        purpose: "Calm focus, edge reduction",
        why: "Here it supports the anxiety edge of a high-stress pattern rather than pure focus enhancement.",
        research: {
          citation: "Kimura et al., Biological Psychology, 2007",
          tested: "L-theanine on physiological stress responses",
          found: "Stress-response markers improved under psychological stress",
          meaning: "Useful before demanding situations when intensity is the issue.",
        },
        timing: "As needed",
      },
    ],
  },
  MODULE_D_GUT: {
    id: "MODULE_D_GUT",
    name: "Gut-Brain Foundation",
    tagline: "For digestive health, immunity, and mood stability",
    ingredients: [
      {
        name: "Probiotic Complex (10B CFU, multi-strain)",
        dose: "10 billion CFU",
        purpose: "Microbiome diversity, immunity, mood support",
        why: "A compromised microbiome often shows up in energy, mood, and digestion at the same time.",
        research: {
          citation: "Cryan et al., Physiological Reviews, 2019",
          tested: "Gut-brain axis and microbiome effects on mood and cognition",
          found: "The microbiome directly influences stress response, mood, and cognition",
          meaning: "This module exists for patterns where digestion and broader function move together.",
        },
        timing: "AM — on empty stomach or with light food",
      },
      {
        name: "Prebiotic (Inulin + FOS)",
        dose: "3g",
        purpose: "Probiotic fuel, gut barrier support",
        why: "Prebiotics feed beneficial strains and improve microbiome durability over time.",
        research: {
          citation: "Slavin, Nutrients, 2013",
          tested: "Prebiotic supplementation on microbiome composition",
          found: "Beneficial bacteria populations increased",
          meaning: "This increases the durability of the probiotic layer rather than duplicating it.",
        },
        timing: "PM — with food",
      },
      {
        name: "N-Acetyl Cysteine (NAC)",
        dose: "500mg",
        purpose: "Antioxidant precursor, gut lining support",
        why: "NAC supports glutathione production and gut barrier integrity. Regulatory inclusion should be confirmed before launch.",
        research: {
          citation: "Martínez-Abundis et al., Oxidative Medicine and Cellular Longevity, 2016",
          tested: "NAC on intestinal permeability and inflammatory markers",
          found: "Gut permeability and oxidative stress markers improved",
          meaning: "This ingredient needs a launch-time regulatory check before shipping.",
        },
        timing: "PM — away from meals",
      },
    ],
  },
  MODULE_E_RECOVERY: {
    id: "MODULE_E_RECOVERY",
    name: "Recovery and Regeneration",
    tagline: "For physical recovery, hormonal balance, and sustained output",
    ingredients: [
      {
        name: "Shilajit (85% Fulvic Acid)",
        dose: "250mg",
        purpose: "Mitochondrial energy, mineral transport",
        why: "Shilajit is studied for recovery and vitality support, but source quality matters materially.",
        research: {
          citation: "Pandit et al., Andrologia, 2016",
          tested: "Shilajit supplementation in healthy volunteers",
          found: "Hormonal markers improved over 90 days",
          meaning: "This is a sourcing-sensitive ingredient and should be used only with verified quality.",
        },
        timing: "AM — with milk or water",
      },
      {
        name: "CoQ10 (Ubiquinol)",
        dose: "100mg",
        purpose: "Cellular energy, muscle recovery",
        why: "In this module CoQ10 supports recovery speed and physical output rather than metabolic stability alone.",
        research: {
          citation: "Gül et al., Journal of the International Society of Sports Nutrition, 2011",
          tested: "CoQ10 supplementation on exercise recovery markers",
          found: "Recovery markers improved in the supplementation group",
          meaning: "Useful when soreness and reload capacity are the recurring complaints.",
        },
        timing: "AM — with food",
      },
      {
        name: "Glycine",
        dose: "3g",
        purpose: "Sleep depth, collagen synthesis, recovery",
        why: "Glycine supports slow-wave sleep and recovery, which is why this module uses a sachet format.",
        research: {
          citation: "Bannai et al., Sleep and Biological Rhythms, 2012",
          tested: "Glycine on sleep quality and next-day alertness",
          found: "Sleep quality and next-day performance improved",
          meaning: "This supports deeper recovery rather than just faster sleep onset.",
        },
        timing: "PM — in the sachet, before bed",
      },
    ],
  },
};
